# Generated by Django 4.0.3 on 2022-04-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreels', '0003_category_role_star_status_remove_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'verbose_name': 'Star'},
        ),
    ]
