# Generated by Django 4.0.3 on 2022-04-13 22:55

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myreels', '0004_alter_star_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('born_date', models.DateField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('role', models.ManyToManyField(to='myreels.role')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneNo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Client',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientOrderedItems', to='myreels.client')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='myreels.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Star',
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='myreels.cast'),
        ),
    ]
