# Generated by Django 4.0.3 on 2022-04-14 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myreels', '0005_cast_client_order_delete_star_alter_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientOrderedItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
